baseurl = "https://techsquad.rocks/"
languageCode = "en-US"
title = "Kubernetes, CI/CD, Git, Linux, Containers, Golang... and more"
# Enable comments by entering your Disqus shortname
disqusShortname = "kainlite"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-8919037-7"
# License
license = "MIT"
licenselink = "https://github.com/kainlite/blog/blob/master/LICENSE.md"

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Gabriel"
  email = "kainlite@gmail.com"
  description = "Articles about Kubernetes, CI/CD, Git, Linux, Containers, Golang, and probably some more random stuff, you can subscribe via RSS or JSON Feed."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "kainlite"
  Email         = "kainlite@gmail.com"
  Twitter       = "kainlite"
  LinkedIn      = "gabrielgarrido"
  Stackoverflow = "kainlite"
  Telegram      = "kainlite"
  Disqus        = "kainlite"

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[outputs]
  home = ["html", "jsonfeed", "rss"]

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
